### ISSUE TITLE
Add disk io tests

### ISSUE THREAD

**Issue by mooniean** [alan-turing-institute/caked#6]

**Comment by crangelsmith** [comment]
LGTM, some thoughts:

We should add a connection between the data transformation (min_max, gaussian blur, etc) and the DiskDataLoader. Eg. the transformation should be given in the instantiation of the class, and passed down into the disk dataset. 

Also, we need docstrings everywhere, copilot is very useful for that.

**Comment by mooniean** [comment]
Done in #11
